import { useMemo } from "react";
import type { DishItem } from "../types";
import { runFetchActiveDishesService, runFetchRestaurantSettingsService } from "../services/admin-data";
import { runFetchNotificationsService } from "../services/admin-notifications";
import { runFetchOrdersService } from "../services/admin-orders";
import { runFetchActiveTablesService, runFetchServerNotificationScopeService } from "../services/admin-scope-tables";
import { runFetchFastEntryResourcesService } from "../services/fast-entry-resources";

type Params = Record<string, any>;

export function useAdminDataFetchers(params: Params) {
  const {
    supabase,
    restaurantId,
    scopedRestaurantId,
    getAccessToken,
    normalizeAssignedTables,
    setServerTableScopeEnabled,
    setServerAssignedTables,
    canAccessAssignedTable,
    setOrders,
    logFetchOrdersError,
    isKitchenOnlyNotification,
    normalizeNotificationRow,
    setServiceNotifications,
    setActiveTables,
    dishes,
    readBooleanFlag,
    setActiveDishNames,
    resolveClientOrderingDisabled,
    resolveTotalTables,
    applyDisableClientOrdering,
    setSettings,
    setTotalTables,
    setRestaurantId,
    setRestaurantSettingsError,
    dishSelectWithOptions,
    dishSelectBase,
    formulasCategoryKey,
    selectedCategory,
    fastEntryInitializedRef,
    selectedCategoryInitializedRef,
    setIsDishesLoading,
    setCategories,
    setDishes,
    setFormulas,
    setFormulaDisplays,
    setFormulaLinksByFormulaId,
    setFormulaLinksByDishId,
    setFormulaDisplayById,
    setFormulaDishIdsFromLinks,
    setFormulaPriceByDishId,
    setSidesLibrary,
    setTableNumbers,
    setSelectedFastTableNumber,
    setDishIdsWithLinkedExtras,
    setSelectedCategory,
    parseJsonObject,
    parsePriceNumber,
    normalizeCategoryKey,
    getCategoryLabel,
    getDishCategoryLabel,
  } = params;

  return useMemo(
    () => ({
      fetchServerNotificationScope: async () =>
        runFetchServerNotificationScopeService({
          restaurantId,
          scopedRestaurantId,
          getAccessToken,
          normalizeAssignedTables,
          setServerTableScopeEnabled,
          setServerAssignedTables,
        }),
      fetchOrders: async () =>
        runFetchOrdersService({
          supabase,
          restaurantId,
          scopedRestaurantId,
          canAccessAssignedTable,
          setOrders,
          logFetchOrdersError,
        }),
      fetchNotifications: async (restaurantScope: string | number | null = restaurantId || scopedRestaurantId || null) =>
        runFetchNotificationsService({
          supabase,
          restaurantScope,
          canAccessAssignedTable,
          isKitchenOnlyNotification,
          normalizeNotificationRow,
          setServiceNotifications,
        }),
      fetchActiveTables: async (restaurantScope: string | number | null = restaurantId || scopedRestaurantId || null) =>
        runFetchActiveTablesService({
          supabase,
          restaurantScope,
          setActiveTables,
        }),
      fetchActiveDishes: async (restaurantScope: string | number | null = restaurantId || scopedRestaurantId || null) =>
        runFetchActiveDishesService({
          restaurantScope,
          dishes: dishes as DishItem[],
          readBooleanFlag,
          setActiveDishNames,
        }),
      fetchRestaurantSettings: async () =>
        runFetchRestaurantSettingsService({
          supabase,
          scopedRestaurantId,
          resolveClientOrderingDisabled,
          resolveTotalTables,
          applyDisableClientOrdering,
          setSettings,
          setTotalTables,
          setRestaurantId,
          setRestaurantSettingsError,
        }),
      fetchFastEntryResources: async () =>
        runFetchFastEntryResourcesService({
          supabase,
          restaurantId,
          scopedRestaurantId,
          dishSelectWithOptions,
          dishSelectBase,
          formulasCategoryKey,
          selectedCategory,
          fastEntryInitializedRef,
          selectedCategoryInitializedRef,
          setIsDishesLoading,
          setCategories,
          setDishes,
          setActiveDishNames,
          setFormulas,
          setFormulaDisplays,
          setFormulaLinksByFormulaId,
          setFormulaLinksByDishId,
          setFormulaDisplayById,
          setFormulaDishIdsFromLinks,
          setFormulaPriceByDishId,
          setSidesLibrary,
          setTableNumbers,
          setSelectedFastTableNumber,
          setDishIdsWithLinkedExtras,
          setSelectedCategory,
          readBooleanFlag,
          parseJsonObject,
          parsePriceNumber,
          normalizeCategoryKey,
          getCategoryLabel,
          getDishCategoryLabel,
        }),
    }),
    [
      supabase,
      restaurantId,
      scopedRestaurantId,
      getAccessToken,
      normalizeAssignedTables,
      setServerTableScopeEnabled,
      setServerAssignedTables,
      canAccessAssignedTable,
      setOrders,
      logFetchOrdersError,
      isKitchenOnlyNotification,
      normalizeNotificationRow,
      setServiceNotifications,
      setActiveTables,
      dishes,
      readBooleanFlag,
      setActiveDishNames,
      resolveClientOrderingDisabled,
      resolveTotalTables,
      applyDisableClientOrdering,
      setSettings,
      setTotalTables,
      setRestaurantId,
      setRestaurantSettingsError,
      dishSelectWithOptions,
      dishSelectBase,
      formulasCategoryKey,
      selectedCategory,
      fastEntryInitializedRef,
      selectedCategoryInitializedRef,
      setIsDishesLoading,
      setCategories,
      setDishes,
      setFormulas,
      setFormulaDisplays,
      setFormulaLinksByFormulaId,
      setFormulaLinksByDishId,
      setFormulaDisplayById,
      setFormulaDishIdsFromLinks,
      setFormulaPriceByDishId,
      setSidesLibrary,
      setTableNumbers,
      setSelectedFastTableNumber,
      setDishIdsWithLinkedExtras,
      setSelectedCategory,
      parseJsonObject,
      parsePriceNumber,
      normalizeCategoryKey,
      getCategoryLabel,
      getDishCategoryLabel,
    ]
  );
}
