begin;

create table if not exists public.formula_dish_links (
  id bigint generated by default as identity primary key,
  formula_dish_id bigint not null,
  dish_id bigint not null,
  restaurant_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_formula_dish_links_formula_id
  on public.formula_dish_links (formula_dish_id);

create index if not exists idx_formula_dish_links_dish_id
  on public.formula_dish_links (dish_id);

create unique index if not exists idx_formula_dish_links_unique
  on public.formula_dish_links (formula_dish_id, dish_id);

do $$
declare
  existing_fk text;
begin
  select tc.constraint_name
    into existing_fk
  from information_schema.table_constraints tc
  join information_schema.key_column_usage kcu
    on tc.constraint_name = kcu.constraint_name
   and tc.table_schema = kcu.table_schema
  join information_schema.constraint_column_usage ccu
    on tc.constraint_name = ccu.constraint_name
   and tc.table_schema = ccu.table_schema
  where tc.table_schema = 'public'
    and tc.table_name = 'formula_dish_links'
    and tc.constraint_type = 'FOREIGN KEY'
    and kcu.column_name = 'formula_dish_id'
    and ccu.table_schema = 'public'
    and ccu.table_name = 'dishes'
  limit 1;

  if existing_fk is not null then
    execute format('alter table public.formula_dish_links drop constraint %I', existing_fk);
  end if;

  execute '
    alter table public.formula_dish_links
    add constraint formula_dish_links_formula_fkey
    foreign key (formula_dish_id)
    references public.dishes(id)
    on delete cascade
  ';

  select tc.constraint_name
    into existing_fk
  from information_schema.table_constraints tc
  join information_schema.key_column_usage kcu
    on tc.constraint_name = kcu.constraint_name
   and tc.table_schema = kcu.table_schema
  join information_schema.constraint_column_usage ccu
    on tc.constraint_name = ccu.constraint_name
   and tc.table_schema = ccu.table_schema
  where tc.table_schema = 'public'
    and tc.table_name = 'formula_dish_links'
    and tc.constraint_type = 'FOREIGN KEY'
    and kcu.column_name = 'dish_id'
    and ccu.table_schema = 'public'
    and ccu.table_name = 'dishes'
  limit 1;

  if existing_fk is not null then
    execute format('alter table public.formula_dish_links drop constraint %I', existing_fk);
  end if;

  execute '
    alter table public.formula_dish_links
    add constraint formula_dish_links_dish_fkey
    foreign key (dish_id)
    references public.dishes(id)
    on delete cascade
  ';
end $$;

notify pgrst, 'reload schema';

commit;
