begin;

create table if not exists public.auth_login_otps (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email text not null,
  scope text not null,
  session_id text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  consumed_at timestamptz null,
  created_at timestamptz not null default now()
);

alter table if exists public.auth_login_otps
  add column if not exists user_id uuid,
  add column if not exists email text,
  add column if not exists scope text,
  add column if not exists session_id text,
  add column if not exists code_hash text,
  add column if not exists expires_at timestamptz,
  add column if not exists consumed_at timestamptz null,
  add column if not exists created_at timestamptz not null default now();

create index if not exists idx_auth_login_otps_lookup
  on public.auth_login_otps (user_id, session_id, scope, created_at desc);

create index if not exists idx_auth_login_otps_active
  on public.auth_login_otps (expires_at, consumed_at);

notify pgrst, 'reload schema';

commit;
