begin;

create table if not exists public.global_notifications (
  id bigint generated by default as identity primary key,
  message text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid null
);

alter table if exists public.global_notifications
  add column if not exists message text,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists created_by uuid null;

create index if not exists idx_global_notifications_active_created_at
  on public.global_notifications (is_active, created_at desc);

notify pgrst, 'reload schema';

commit;
