export const MENU_PAGE_UI_TEXT = {
  fr: {
    categories: ["Tous", "Entrées", "Plats", "Desserts", "Boissons"],
    labels: {
      all: "Tous",
      others: "Autres",
      order_success: "Votre commande a été envoyée avec succès. Votre plat va bientôt arriver. Bon appétit.",
      order_confirmed: "Votre commande a été envoyée avec succès. Votre plat va bientôt arriver. Bon appétit.",
      order_success_message: "Votre commande a été envoyée avec succès ! Table {table}. Bon appétit !",
      consultation_mode_banner: "La commande se fait auprès de votre serveur. Utilisez ce menu pour découvrir nos plats !",
      validation_code_prompt: "Saisissez le code PIN de votre table pour valider la commande.",
      validation_code_label: "Code PIN",
      validation_code_placeholder: "Code PIN",
      validation_code_invalid: "Code PIN incorrect.",
      table_required: "Veuillez renseigner votre table.",
      table_invalid: "Numéro de table invalide.",
      empty_cart_error: "Votre panier est vide.",
      side_required_error: "Veuillez choisir un accompagnement obligatoire.",
      cooking_required_error: "Veuillez choisir une cuisson.",
      max_options_error: "Maximum {max} options.",
      server_called_success: "Serveur appelé !",
      generic_error: "Erreur.",
      supabase_error_prefix: "Erreur Supabase :",
      item_added: "Article ajouté !",
      added: "Ajouté au panier",
      details_label: "Précisions",
      details_none: "Aucune demande particulière.",
      pin_required_cart: "Renseignez la table et le code PIN avant d'ajouter un article.",
      loading: "Chargement...",
      featured_daily: "Plat du Jour",
      featured_chef: "Suggestion du Chef",
      sales_advice_title: "Conseil du Chef",
      sales_advice_view_item: "Voir l'article",
      vegetarian: "Végétarien",
      spicy: "Pimenté",
      select_sides_up_to: "Choisissez jusqu'à {max} choix",
      select_sides_up_to_icecream: "Choisissez jusqu'à {max} parfums",
      no_side_configured: "Aucun accompagnement configuré pour ce plat.",
      formulas: "Formules",
      available_in_formula: "Disponible en formule",
      view_formula: "Voir la formule",
      formula_name: "Nom de la formule",
      formula_image: "Image de la formule",
      view_formula_offer: "Voir l'offre en formule",
      order_in_formula: "Commander en formule",
      item_details: "Détails de l'article",
      formula_option_locked: "Supplément indisponible en formule",
    },
    categoryMap: {
      all: "Tous",
      tous: "Tous",
      entree: "Entrées",
      entrees: "Entrées",
      plats: "Plats",
      plat: "Plats",
      dessert: "Desserts",
      desserts: "Desserts",
      boisson: "Boissons",
      boissons: "Boissons",
      starters: "Entrées",
      mains: "Plats",
      drinks: "Boissons",
    },
    subcategoryMap: {
      autres: "Autres",
      other: "Autres",
      others: "Autres",
    },
    addToCart: "Ajouter au panier",
    cart: "Panier",
    total: "Total",
    order: "Commander",
    backToMenu: "Retour au menu",
    menu: "Menu",
    callServer: "Appeler le serveur",
    help: "Besoin d'aide ?",
    categoriesTitle: "Catégories",
    close: "Fermer",
    quantity: "Quantité",
    emptyCart: "Votre panier est vide.",
    noDishes: "Aucun plat disponible.",
    specialRequestLabel: "Demande spéciale",
    specialRequestPlaceholder: "Ex : sans oignons, sauce à part...",
    sidesLabel: "Accompagnements",
    allergensLabel: "Allerg&egrave;nes",
    extraLabel: "Supplément",
    extrasLabel: "Suppléments",
    table: "Table",
    pin: "Code PIN",
    yourTable: "Votre Table",
    pinCode: "Code PIN",
    hunger: {
      small: "Petite faim",
      medium: "Moyenne faim",
      large: "Grande faim",
    },
    cookingLabel: "Cuisson",
    cooking: {
      blue: "Bleu",
      rare: "Saignant",
      medium: "À point",
      wellDone: "Bien cuit",
    },
  },
  en: {
    categories: ["All", "Starters", "Mains", "Desserts", "Drinks"],
    labels: {
      all: "All",
      others: "Others",
      order_success: "Your order has been sent successfully. Your dish will arrive soon. Enjoy your meal.",
      order_confirmed: "Your order has been sent successfully. Your dish will arrive soon. Enjoy your meal.",
      order_success_message: "Your order has been sent successfully! Table {table}. Enjoy your meal!",
      consultation_mode_banner: "Please order directly with your server. Use this menu to discover our dishes!",
      validation_code_prompt: "Enter your table PIN code to confirm the order.",
      validation_code_label: "PIN code",
      validation_code_placeholder: "PIN code",
      validation_code_invalid: "Invalid PIN code.",
      table_required: "Please enter your table number.",
      table_invalid: "Invalid table number.",
      empty_cart_error: "Your cart is empty.",
      side_required_error: "Please choose a required side.",
      cooking_required_error: "Please choose a cooking level.",
      max_options_error: "Maximum {max} options.",
      server_called_success: "Server called!",
      generic_error: "Error.",
      supabase_error_prefix: "Supabase error:",
      item_added: "Item added!",
      added: "Added to cart",
      details_label: "Details",
      details_none: "No special request.",
      pin_required_cart: "Enter table number and a valid PIN code before adding an item.",
      loading: "Loading...",
      featured_daily: "Dish of the Day",
      featured_chef: "Chef Suggestion",
      sales_advice_title: "Chef's recommendation",
      sales_advice_view_item: "View item",
      vegetarian: "Vegetarian",
      spicy: "Spicy",
      select_sides_up_to: "Choose up to {max} options",
      select_sides_up_to_icecream: "Choose up to {max} flavors",
      no_side_configured: "No side configured for this dish.",
      formulas: "Menus",
      available_in_formula: "Available in formula",
      view_formula: "View menu",
      formula_name: "Formula name",
      formula_image: "Formula image",
      view_formula_offer: "View formula offer",
      order_in_formula: "Order as set menu",
      item_details: "Item details",
      formula_option_locked: "Extra not available in set menu",
    },
    categoryMap: {
      all: "All",
      tous: "All",
      entree: "Starters",
      entrees: "Starters",
      plats: "Mains",
      plat: "Mains",
      dessert: "Desserts",
      desserts: "Desserts",
      boisson: "Drinks",
      boissons: "Drinks",
      starters: "Starters",
      mains: "Mains",
      drinks: "Drinks",
    },
    subcategoryMap: {
      autres: "Others",
      other: "Others",
      others: "Others",
    },
    addToCart: "Add to cart",
    cart: "Cart",
    total: "Total",
    order: "Order",
    backToMenu: "Back to menu",
    menu: "Menu",
    callServer: "Call the server",
    help: "Need help?",
    categoriesTitle: "Categories",
    close: "Close",
    quantity: "Quantity",
    emptyCart: "Your cart is empty.",
    noDishes: "No dishes available.",
    specialRequestLabel: "Special request",
    specialRequestPlaceholder: "Ex: no onions, sauce on the side...",
    sidesLabel: "Sides",
    allergensLabel: "Allergens",
    extraLabel: "Extra",
    extrasLabel: "Extras",
    table: "Table",
    pin: "PIN code",
    yourTable: "Your Table",
    pinCode: "PIN Code",
    hunger: {
      small: "Small appetite",
      medium: "Medium appetite",
      large: "Large appetite",
    },
    cookingLabel: "Cooking",
    cooking: {
      blue: "Blue",
      rare: "Rare",
      medium: "Medium",
      wellDone: "Well done",
    },
  },
  es: {
    categories: ["Todos", "Entrantes", "Platos", "Postres", "Bebidas"],
    labels: {
      all: "Todos",
      others: "Otros",
      order_success: "Tu pedido se ha enviado con éxito. Tu plato llegará pronto. Buen provecho.",
      order_confirmed: "Tu pedido se ha enviado con éxito. Tu plato llegará pronto. Buen provecho.",
      order_success_message: "¡Tu pedido se ha enviado con éxito! Mesa {table}. ¡Buen provecho!",
      consultation_mode_banner: "El pedido se realiza con su camarero. ¡Use este menú para descubrir nuestros platos!",
      validation_code_prompt: "Introduzca el código PIN de su mesa para validar el pedido.",
      validation_code_label: "Código PIN",
      validation_code_placeholder: "Código PIN",
      validation_code_invalid: "Código PIN incorrecto.",
      table_required: "Indique su número de mesa.",
      table_invalid: "Número de mesa inválido.",
      empty_cart_error: "Tu carrito está vacío.",
      side_required_error: "Seleccione un acompañamiento obligatorio.",
      cooking_required_error: "Seleccione un punto de cocción.",
      max_options_error: "Máximo {max} opciones.",
      server_called_success: "¡Camarero avisado!",
      generic_error: "Error.",
      supabase_error_prefix: "Error de Supabase:",
      item_added: "¡Artículo añadido!",
      added: "Añadido al carrito",
      details_label: "Detalles",
      details_none: "Sin petición especial.",
      pin_required_cart: "Indique mesa y código PIN válido antes de añadir un artículo.",
      loading: "Cargando...",
      featured_daily: "Plato del Día",
      featured_chef: "Sugerencia del Chef",
      sales_advice_title: "Consejo del chef",
      sales_advice_view_item: "Ver artículo",
      vegetarian: "Vegetariano",
      spicy: "Picante",
      select_sides_up_to: "Elige hasta {max} opciones",
      select_sides_up_to_icecream: "Elige hasta {max} sabores",
      no_side_configured: "No hay acompañamiento configurado para este plato.",
      formulas: "Menús",
      available_in_formula: "Disponible en fórmula",
      view_formula: "Ver el menú",
      formula_name: "Nombre de la fórmula",
      formula_image: "Imagen de la fórmula",
      view_formula_offer: "Ver la oferta en fórmula",
      order_in_formula: "Pedir en menú",
      item_details: "Detalles del artículo",
      formula_option_locked: "Suplemento no disponible en el menú",
    },
    categoryMap: {
      all: "Todos",
      todos: "Todos",
      entree: "Entrantes",
      entrees: "Entrantes",
      platos: "Platos",
      plat: "Platos",
      dessert: "Postres",
      desserts: "Postres",
      boisson: "Bebidas",
      boissons: "Bebidas",
      starters: "Entrantes",
      mains: "Platos",
      drinks: "Bebidas",
    },
    subcategoryMap: {
      autres: "Otros",
      other: "Otros",
      others: "Otros",
    },
    addToCart: "Añadir al carrito",
    cart: "Carrito",
    total: "Total",
    order: "Pedir",
    backToMenu: "Volver al menú",
    menu: "Menú",
    callServer: "Llamar al camarero",
    help: "¿Necesitas ayuda?",
    categoriesTitle: "Categorías",
    close: "Cerrar",
    quantity: "Cantidad",
    emptyCart: "Tu carrito está vacío.",
    noDishes: "No hay platos disponibles.",
    specialRequestLabel: "Petición especial",
    specialRequestPlaceholder: "Ej: sin cebolla, salsa aparte...",
    sidesLabel: "Acompañamientos",
    allergensLabel: "Alérgenos",
    extraLabel: "Suplemento",
    extrasLabel: "Suplementos",
    table: "Mesa",
    pin: "Código PIN",
    yourTable: "Su Mesa",
    pinCode: "Código PIN",
    hunger: {
      small: "Poca hambre",
      medium: "Hambre media",
      large: "Mucha hambre",
    },
    cookingLabel: "Cocción",
    cooking: {
      blue: "Poco hecho",
      rare: "Poco cocido",
      medium: "En su punto",
      wellDone: "Bien cocido",
    },
  },
  de: {
    categories: ["Alle", "Vorspeisen", "Hauptgerichte", "Desserts", "Getränke"],
    labels: {
      all: "Alle",
      others: "Andere",
      order_success: "Ihre Bestellung wurde erfolgreich gesendet. Ihr Gericht kommt bald. Guten Appetit.",
      order_confirmed: "Ihre Bestellung wurde erfolgreich gesendet. Ihr Gericht kommt bald. Guten Appetit.",
      order_success_message: "Ihre Bestellung wurde erfolgreich gesendet! Tisch {table}. Guten Appetit!",
      consultation_mode_banner: "Bestellen Sie bitte direkt beim Service. Nutzen Sie dieses Menü, um unsere Gerichte zu entdecken!",
      validation_code_prompt: "Geben Sie den PIN-Code Ihres Tisches ein, um die Bestellung zu bestätigen.",
      validation_code_label: "PIN-Code",
      validation_code_placeholder: "PIN-Code",
      validation_code_invalid: "Ungültiger PIN-Code.",
      table_required: "Bitte geben Sie Ihre Tischnummer ein.",
      table_invalid: "Ungültige Tischnummer.",
      empty_cart_error: "Ihr Warenkorb ist leer.",
      side_required_error: "Bitte wählen Sie eine Beilage aus.",
      cooking_required_error: "Bitte wählen Sie eine Garstufe.",
      max_options_error: "Maximal {max} Optionen.",
      server_called_success: "Service gerufen!",
      generic_error: "Fehler.",
      supabase_error_prefix: "Supabase-Fehler:",
      item_added: "Artikel hinzugefügt!",
      added: "In den Warenkorb",
      details_label: "Details",
      details_none: "Keine besondere Anfrage.",
      pin_required_cart: "Geben Sie Tischnummer und gültigen PIN-Code ein, bevor Sie einen Artikel hinzufügen.",
      loading: "Wird geladen...",
      featured_daily: "Tagesgericht",
      featured_chef: "Empfehlung des Chefs",
      sales_advice_title: "Empfehlung des Küchenchefs",
      sales_advice_view_item: "Artikel ansehen",
      vegetarian: "Vegetarisch",
      spicy: "Scharf",
      select_sides_up_to: "Wählen Sie bis zu {max} Optionen",
      select_sides_up_to_icecream: "Wählen Sie bis zu {max} Sorten",
      no_side_configured: "Keine Beilage für dieses Gericht konfiguriert.",
      formulas: "Menüs",
      available_in_formula: "In Formel verfügbar",
      view_formula: "Menü ansehen",
      formula_name: "Formelname",
      formula_image: "Formelbild",
      view_formula_offer: "Formelangebot ansehen",
      order_in_formula: "Als Menü bestellen",
      item_details: "Artikeldetails",
      formula_option_locked: "Aufpreis im Menü nicht verfügbar",
    },
    categoryMap: {
      all: "Alle",
      tous: "Alle",
      entree: "Vorspeisen",
      entrees: "Vorspeisen",
      plat: "Hauptgerichte",
      plats: "Hauptgerichte",
      dessert: "Desserts",
      desserts: "Desserts",
      boisson: "Getränke",
      boissons: "Getränke",
      starters: "Vorspeisen",
      mains: "Hauptgerichte",
      drinks: "Getränke",
    },
    subcategoryMap: {
      autres: "Andere",
      other: "Andere",
      others: "Andere",
    },
    addToCart: "In den Warenkorb",
    cart: "Warenkorb",
    total: "Summe",
    order: "Bestellen",
    backToMenu: "Zurück zum Menü",
    menu: "Menü",
    callServer: "Service rufen",
    help: "Hilfe benötigt?",
    categoriesTitle: "Kategorien",
    close: "Schließen",
    quantity: "Menge",
    emptyCart: "Ihr Warenkorb ist leer.",
    noDishes: "Keine Gerichte verfügbar.",
    specialRequestLabel: "Besonderer Wunsch",
    specialRequestPlaceholder: "Z.B. ohne Zwiebeln, Sauce extra...",
    sidesLabel: "Beilagen",
    allergensLabel: "Allergènes",
    extraLabel: "Extra",
    extrasLabel: "Extras",
    table: "Tisch",
    pin: "PIN-Code",
    yourTable: "Ihr Tisch",
    pinCode: "PIN-Code",
    hunger: {
      small: "Kleiner Hunger",
      medium: "Mittlerer Hunger",
      large: "Großer Hunger",
    },
    cookingLabel: "Garstufe",
    cooking: {
      blue: "Sehr blutig",
      rare: "Blutig",
      medium: "Medium",
      wellDone: "Durchgebraten",
    },
  },
} as const;
