export function buildManagerDishFetchArgs(params: any) {
  const { runtime, refs, setters, helpers, managerEditorUiState, state } = params;
  return {
    scopedRestaurantId: runtime.scopedRestaurantId,
    supabase: runtime.supabase,
    setCategories: setters.setCategories,
    setFormulaLinksByFormulaId: setters.setFormulaLinksByFormulaId,
    setFormulaLinksByDishId: setters.setFormulaLinksByDishId,
    setFormulaLinkDefaultOptionsByFormulaId: setters.setFormulaLinkDefaultOptionsByFormulaId,
    setFormulaMainDishOptionsByFormulaId: setters.setFormulaMainDishOptionsByFormulaId,
    setFormulaLinkDisplayByFormulaId: setters.setFormulaLinkDisplayByFormulaId,
    setFormulaLinkSequenceByFormulaId: setters.setFormulaLinkSequenceByFormulaId,
    hasMissingColumnError: helpers.hasMissingColumnError,
    toLoggableSupabaseError: helpers.toLoggableSupabaseError,
    toBoolean: helpers.toBoolean,
    parseJsonObject: helpers.parseJsonObject,
    parseExtrasFromUnknown: helpers.parseExtrasFromUnknown,
    dishesRefetchLockUntilRef: refs.dishesRefetchLockUntilRef,
    lastSaveTimeRef: refs.lastSaveTimeRef,
    isSavingRef: refs.isSavingRef,
    setDishes: setters.setDishes,
    parseDishOptionsRowsToExtras: helpers.parseDishOptionsRowsToExtras,
    createLocalId: helpers.createLocalId,
    parseObjectRecord: helpers.parseObjectRecord,
    parseI18nToken: helpers.parseI18nToken,
    normalizeLanguageKey: helpers.normalizeLanguageKey,
    extractFormulaProductOptionsForManager: helpers.extractFormulaProductOptionsForManager,
    mergeExtrasUnique: helpers.mergeExtrasUnique,
    mergeProductOptions: helpers.mergeProductOptions,
    extractAllergenNamesFromDishPayload: helpers.extractAllergenNamesFromDishPayload,
    normalizeText: helpers.normalizeText,
    mergeAllergenLibraryRows: helpers.mergeAllergenLibraryRows,
    setAllergenLibrary: setters.setAllergenLibrary,
    editingDish: managerEditorUiState.editingDish,
    showDishModal: managerEditorUiState.showDishModal,
    formData: managerEditorUiState.formData,
    excludedMainOptionsTouched: managerEditorUiState.excludedMainOptionsTouched,
    isRadarLoaded: managerEditorUiState.isRadarLoaded,
    selectedMainDishOptions: managerEditorUiState.selectedMainDishOptions,
    setSelectedMainDishOptions: managerEditorUiState.setSelectedMainDishOptions,
    formulaMainDishOptionsByFormulaId: state.formulaMainDishOptionsByFormulaId,
  };
}
