export function buildManagerSharedBundles(source: any) {
  const managerSharedState = {
    categories: source.categories,
    dishes: source.dishes,
    subCategoryRows: source.subCategoryRows,
    sides: source.sidesLibrary,
    sidesLibrary: source.sidesLibrary,
    restaurant: source.restaurant,
    restaurantForm: source.restaurantForm,
    reviews: source.reviews,
    managerUserEmail: source.managerUserEmail,
    managerOtpEnabled: source.managerOtpEnabled,
    managerOtpError: source.managerOtpError,
    managerOtpLoading: source.managerOtpLoading,
    managerOtpMessage: source.managerOtpMessage,
    passwordForm: source.passwordForm,
    passwordUpdateError: source.passwordUpdateError,
    passwordUpdateLoading: source.passwordUpdateLoading,
    passwordUpdateMessage: source.passwordUpdateMessage,
    globalManagerNotification: source.globalManagerNotification,
    isRestaurantLoading: source.isRestaurantLoading,
    managerAccessError: source.managerAccessError,
    forceFirstLoginPasswordChange: source.forceFirstLoginPasswordChange,
    isPurgingHistory: source.isPurgingHistory,
    activeLanguageCodes: source.activeLanguageCodes,
    languagePresetToAdd: source.languagePresetToAdd,
    allergenLibrary: source.allergenLibrary,
    newAllergenFr: source.newAllergenFr,
    cookingTranslations: source.cookingTranslations,
    searchBarEnabled: source.searchBarEnabled,
    autoPrintKitchen: source.autoPrintKitchen,
    consultationModeEnabled: source.consultationModeEnabled,
    showCaloriesClient: source.showCaloriesClient,
    languageLabels: source.languageLabels,
    heroEnabled: source.heroEnabled,
    heroBadgeType: source.heroBadgeType,
    totalTables: source.totalTables,
    isSuperAdminSession: source.isSuperAdminSession,
  };

  const managerSharedSetters = {
    setActiveManagerTab: source.setActiveManagerTab,
    setAnalyticsRange: source.setAnalyticsRange,
    setAnalyticsTab: source.setAnalyticsTab,
    setTotalTables: source.setTotalTables,
    setRestaurantForm: source.setRestaurantForm,
    setActiveLanguageCodes: source.setActiveLanguageCodes,
    setLanguageLabels: source.setLanguageLabels,
    setLanguagePresetToAdd: source.setLanguagePresetToAdd,
    setAutoPrintKitchen: source.setAutoPrintKitchen,
    setConsultationModeEnabled: source.setConsultationModeEnabled,
    setCookingTranslations: source.setCookingTranslations,
    setHeroBadgeType: source.setHeroBadgeType,
    setHeroEnabled: source.setHeroEnabled,
    setSearchBarEnabled: source.setSearchBarEnabled,
    setShowCaloriesClient: source.setShowCaloriesClient,
    setNewAllergenFr: source.setNewAllergenFr,
    setPasswordForm: source.setPasswordForm,
    setShowDeleteModal: source.setShowDeleteModal,
    setDishToDelete: source.setDishToDelete,
    setAllergenLibrary: source.setAllergenLibrary,
    setRestaurant: source.setRestaurant,
    setPasswordUpdateError: source.setPasswordUpdateError,
    setPasswordUpdateMessage: source.setPasswordUpdateMessage,
    setPasswordUpdateLoading: source.setPasswordUpdateLoading,
    setForceFirstLoginPasswordChange: source.setForceFirstLoginPasswordChange,
    setManagerOtpError: source.setManagerOtpError,
    setManagerOtpMessage: source.setManagerOtpMessage,
    setManagerOtpLoading: source.setManagerOtpLoading,
    setManagerOtpEnabled: source.setManagerOtpEnabled,
    setMigrating: source.setMigrating,
  };

  const managerSharedHelpers = {
    renderReviewStars: source.renderReviewStars,
    formatEuro: source.formatEuro,
    toBoolean: source.toBoolean,
    parseI18nToken: source.parseI18nToken,
    normalizeText: source.normalizeText,
    normalizeLanguageKey: source.normalizeLanguageKey,
    normalizeTotalTables: source.normalizeTotalTables,
    normalizeCategoryDestination: source.normalizeCategoryDestination,
    normalizeSortOrder: source.normalizeSortOrder,
    normalizeCardStyle: source.normalizeCardStyle,
    normalizeManagerFontFamily: source.normalizeManagerFontFamily,
    normalizeOpacityPercent: source.normalizeOpacityPercent,
    normalizeWelcomePopupType: source.normalizeWelcomePopupType,
    parseObjectRecord: source.parseObjectRecord,
    createLocalId: source.createLocalId,
    normalizeHexColor: source.normalizeHexColor,
    normalizeTimeInput: source.normalizeTimeInput,
    normalizeDensityStyle: source.normalizeDensityStyle,
    normalizeBackgroundOpacity: source.normalizeBackgroundOpacity,
    normalizeMenuLayout: source.normalizeMenuLayout,
    normalizeCardLayout: source.normalizeCardLayout,
    isMissingTableError: source.isMissingTableError,
    hasMissingColumnError: source.hasMissingColumnError,
    writeLocalClientOrderingDisabled: source.writeLocalClientOrderingDisabled,
    extractMissingColumnName: source.extractMissingColumnName,
  };

  const managerSharedConstants = {
    MAX_TOTAL_TABLES: source.MAX_TOTAL_TABLES,
    DEFAULT_TOTAL_TABLES: source.DEFAULT_TOTAL_TABLES,
    DEFAULT_LANGUAGE_LABELS: source.DEFAULT_LANGUAGE_LABELS,
    DEFAULT_COOKING_TRANSLATIONS: source.DEFAULT_COOKING_TRANSLATIONS,
    COOKING_TRANSLATION_ORDER: source.COOKING_TRANSLATION_ORDER,
    MENU_FONT_OPTIONS: source.MENU_FONT_OPTIONS,
    PREDEFINED_LANGUAGE_OPTIONS: source.PREDEFINED_LANGUAGE_OPTIONS,
    DISH_AVAILABLE_DAY_OPTIONS: source.DISH_AVAILABLE_DAY_OPTIONS,
    HUNGER_LEVELS: source.HUNGER_LEVELS,
    STANDARD_FORMULA_ALLERGENS: source.STANDARD_FORMULA_ALLERGENS,
    ALLERGEN_OPTIONS: source.ALLERGEN_OPTIONS,
    FORMULA_PARENT_STEP_KEY: source.FORMULA_PARENT_STEP_KEY,
    FORMULA_DIRECT_SEND_SEQUENCE: source.FORMULA_DIRECT_SEND_SEQUENCE,
    DISH_IMAGES_BUCKET: source.DISH_IMAGES_BUCKET,
  };

  return { managerSharedState, managerSharedSetters, managerSharedHelpers, managerSharedConstants };
}
