export function buildManagerRestaurantFetchArgs(params: any) {
  const { runtime, setters, refs, helpers, constants, loadDisplaySettingsFromDb } = params;
  return {
    scopedRestaurantId: runtime.scopedRestaurantId,
    supabase: runtime.supabase,
    setIsRestaurantLoading: setters.setIsRestaurantLoading,
    setIsSuperAdminSession: setters.setIsSuperAdminSession,
    setManagerAccessError: setters.setManagerAccessError,
    setRestaurant: setters.setRestaurant,
    toLoggableSupabaseError: helpers.toLoggableSupabaseError,
    normalizeRestaurantId: helpers.normalizeRestaurantId,
    impersonateMode: runtime.impersonateMode,
    parseObjectRecord: helpers.parseObjectRecord,
    normalizeDensityStyle: helpers.normalizeDensityStyle,
    normalizeManagerFontFamily: helpers.normalizeManagerFontFamily,
    normalizeBackgroundOpacity: helpers.normalizeBackgroundOpacity,
    normalizeCardStyle: helpers.normalizeCardStyle,
    normalizeHexColor: helpers.normalizeHexColor,
    normalizeOpacityPercent: helpers.normalizeOpacityPercent,
    toBoolean: helpers.toBoolean,
    setManagerOtpEnabled: setters.setManagerOtpEnabled,
    setManagerOtpError: setters.setManagerOtpError,
    setForceFirstLoginPasswordChange: setters.setForceFirstLoginPasswordChange,
    parseCategoryConfig: helpers.parseCategoryConfig,
    parseAutoPrintSetting: helpers.parseAutoPrintSetting,
    setAutoPrintKitchen: setters.setAutoPrintKitchen,
    setSearchBarEnabled: setters.setSearchBarEnabled,
    loadDisplaySettingsFromDb,
    setSubCategories: setters.setSubCategories,
    setCookingTranslations: setters.setCookingTranslations,
    parseCookingTranslations: helpers.parseCookingTranslations,
    parseAllergenLibrary: helpers.parseAllergenLibrary,
    setAllergenLibrary: setters.setAllergenLibrary,
    createDefaultAllergenLibrary: helpers.createDefaultAllergenLibrary,
    hasRestaurantLanguagesTableRef: refs.hasRestaurantLanguagesTableRef,
    hasMissingColumnError: helpers.hasMissingColumnError,
    isMissingTableError: helpers.isMissingTableError,
    setActiveLanguageCodes: setters.setActiveLanguageCodes,
    setLanguageLabels: setters.setLanguageLabels,
    normalizeLanguageKey: helpers.normalizeLanguageKey,
    DEFAULT_LANGUAGE_LABELS: constants.DEFAULT_LANGUAGE_LABELS,
    setRestaurantForm: setters.setRestaurantForm,
    normalizeWelcomePopupType: helpers.normalizeWelcomePopupType,
    resolveSupabasePublicUrl: helpers.resolveSupabasePublicUrl,
    RESTAURANT_BANNERS_BUCKET: constants.RESTAURANT_BANNERS_BUCKET,
    normalizeMenuLayout: helpers.normalizeMenuLayout,
    parseCardLayoutToken: helpers.parseCardLayoutToken,
  };
}
