import { parseI18nToken } from "../../managerRuntimeShared";
import { formatEuro, renderManagerReviewStars } from "../manager-formatters";
import { normalizeTimeInput } from "../manager-schedule-utils";
import { hasMissingColumnError, isMissingTableError, toBoolean, writeLocalClientOrderingDisabled, extractMissingColumnName } from "../runtime-data-utils";
import {
  ALLERGEN_OPTIONS,
  COOKING_TRANSLATION_ORDER,
  DEFAULT_COOKING_TRANSLATIONS,
  DEFAULT_TOTAL_TABLES,
  DISH_AVAILABLE_DAY_OPTIONS,
  DISH_IMAGES_BUCKET,
  FORMULA_DIRECT_SEND_SEQUENCE,
  FORMULA_PARENT_STEP_KEY,
  HUNGER_LEVELS,
  MAX_TOTAL_TABLES,
  MENU_FONT_OPTIONS,
  PREDEFINED_LANGUAGE_OPTIONS,
  STANDARD_FORMULA_ALLERGENS,
  normalizeBackgroundOpacity,
  normalizeCardLayout,
  normalizeCardStyle,
  normalizeDensityStyle,
  normalizeHexColor,
  normalizeManagerFontFamily,
  normalizeMenuLayout,
  normalizeOpacityPercent,
  normalizeTotalTables,
  normalizeWelcomePopupType,
  parseObjectRecord,
} from "../runtime-core-utils";
import { DEFAULT_LANGUAGE_LABELS, createLocalId, normalizeLanguageKey, normalizeText } from "../../managerRuntimeShared";
import { normalizeCategoryDestination, normalizeSortOrder } from "../manager-category-utils";

export function buildManagerSharedBundlesConfig({
  managerCoreState,
  managerEditorUiState,
}: {
  managerCoreState: any;
  managerEditorUiState: any;
}) {
  const { state, setters } = managerCoreState;

  return {
    categories: state.categories,
    dishes: state.dishes,
    subCategoryRows: state.subCategoryRows,
    sidesLibrary: state.sidesLibrary,
    restaurant: state.restaurant,
    restaurantForm: state.restaurantForm,
    reviews: state.reviews,
    managerUserEmail: state.managerUserEmail,
    managerOtpEnabled: state.managerOtpEnabled,
    managerOtpError: state.managerOtpError,
    managerOtpLoading: state.managerOtpLoading,
    managerOtpMessage: state.managerOtpMessage,
    passwordForm: state.passwordForm,
    passwordUpdateError: state.passwordUpdateError,
    passwordUpdateLoading: state.passwordUpdateLoading,
    passwordUpdateMessage: state.passwordUpdateMessage,
    globalManagerNotification: state.globalManagerNotification,
    isRestaurantLoading: state.isRestaurantLoading,
    managerAccessError: state.managerAccessError,
    forceFirstLoginPasswordChange: state.forceFirstLoginPasswordChange,
    isPurgingHistory: state.isPurgingHistory,
    activeLanguageCodes: state.activeLanguageCodes,
    languagePresetToAdd: state.languagePresetToAdd,
    allergenLibrary: state.allergenLibrary,
    newAllergenFr: state.newAllergenFr,
    cookingTranslations: state.cookingTranslations,
    searchBarEnabled: state.searchBarEnabled,
    autoPrintKitchen: state.autoPrintKitchen,
    consultationModeEnabled: state.consultationModeEnabled,
    showCaloriesClient: state.showCaloriesClient,
    languageLabels: state.languageLabels,
    heroEnabled: state.heroEnabled,
    heroBadgeType: state.heroBadgeType,
    totalTables: state.totalTables,
    isSuperAdminSession: state.isSuperAdminSession,
    setActiveManagerTab: setters.setActiveManagerTab,
    setAnalyticsRange: setters.setAnalyticsRange,
    setAnalyticsTab: setters.setAnalyticsTab,
    setTotalTables: setters.setTotalTables,
    setRestaurantForm: setters.setRestaurantForm,
    setActiveLanguageCodes: setters.setActiveLanguageCodes,
    setLanguageLabels: setters.setLanguageLabels,
    setLanguagePresetToAdd: setters.setLanguagePresetToAdd,
    setAutoPrintKitchen: setters.setAutoPrintKitchen,
    setConsultationModeEnabled: setters.setConsultationModeEnabled,
    setCookingTranslations: setters.setCookingTranslations,
    setHeroBadgeType: setters.setHeroBadgeType,
    setHeroEnabled: setters.setHeroEnabled,
    setSearchBarEnabled: setters.setSearchBarEnabled,
    setShowCaloriesClient: setters.setShowCaloriesClient,
    setNewAllergenFr: setters.setNewAllergenFr,
    setPasswordForm: setters.setPasswordForm,
    setShowDeleteModal: managerEditorUiState.setShowDeleteModal,
    setDishToDelete: managerEditorUiState.setDishToDelete,
    setAllergenLibrary: setters.setAllergenLibrary,
    setRestaurant: setters.setRestaurant,
    setPasswordUpdateError: setters.setPasswordUpdateError,
    setPasswordUpdateMessage: setters.setPasswordUpdateMessage,
    setPasswordUpdateLoading: setters.setPasswordUpdateLoading,
    setForceFirstLoginPasswordChange: setters.setForceFirstLoginPasswordChange,
    setManagerOtpError: setters.setManagerOtpError,
    setManagerOtpMessage: setters.setManagerOtpMessage,
    setManagerOtpLoading: setters.setManagerOtpLoading,
    setManagerOtpEnabled: setters.setManagerOtpEnabled,
    setMigrating: setters.setMigrating,
    renderReviewStars: renderManagerReviewStars,
    formatEuro,
    toBoolean,
    parseI18nToken,
    normalizeText,
    normalizeLanguageKey,
    normalizeTotalTables,
    normalizeCategoryDestination,
    normalizeSortOrder,
    normalizeCardStyle,
    normalizeManagerFontFamily,
    normalizeOpacityPercent,
    normalizeWelcomePopupType,
    parseObjectRecord,
    createLocalId,
    normalizeHexColor,
    normalizeTimeInput,
    normalizeDensityStyle,
    normalizeBackgroundOpacity,
    normalizeMenuLayout,
    normalizeCardLayout,
    isMissingTableError,
    hasMissingColumnError,
    writeLocalClientOrderingDisabled,
    extractMissingColumnName,
    MAX_TOTAL_TABLES,
    DEFAULT_TOTAL_TABLES,
    DEFAULT_LANGUAGE_LABELS,
    DEFAULT_COOKING_TRANSLATIONS,
    COOKING_TRANSLATION_ORDER,
    MENU_FONT_OPTIONS,
    PREDEFINED_LANGUAGE_OPTIONS,
    DISH_AVAILABLE_DAY_OPTIONS,
    HUNGER_LEVELS,
    STANDARD_FORMULA_ALLERGENS,
    ALLERGEN_OPTIONS,
    FORMULA_PARENT_STEP_KEY,
    FORMULA_DIRECT_SEND_SEQUENCE,
    DISH_IMAGES_BUCKET,
  };
}
