export function buildManagerDishEditorLoadArgs(params: any) {
  const { managerEditorUiState, runtime, formulaMaps, helpers, core } = params;
  return {
    ...managerEditorUiState,
    parseOptionsFromDescription: helpers.parseOptionsFromDescription,
    parseObjectRecord: helpers.parseObjectRecord,
    parseHungerLevels: helpers.parseHungerLevels,
    normalizeHungerLevel: helpers.normalizeHungerLevel,
    resolveLegacyHungerLevelLabel: helpers.resolveLegacyHungerLevelLabel,
    parseJsonObject: helpers.parseJsonObject,
    activeLanguageCodes: runtime.activeLanguageCodes,
    normalizeLanguageKey: helpers.normalizeLanguageKey,
    getLanguageColumnKeys: helpers.getLanguageColumnKeys,
    toBoolean: helpers.toBoolean,
    formulaLinksByDishId: formulaMaps.formulaLinksByDishId,
    formulaLinksByFormulaId: formulaMaps.formulaLinksByFormulaId,
    formulaLinkSequenceByFormulaId: formulaMaps.formulaLinkSequenceByFormulaId,
    formulaLinkDefaultOptionsByFormulaId: formulaMaps.formulaLinkDefaultOptionsByFormulaId,
    formulaLinkDisplayByFormulaId: formulaMaps.formulaLinkDisplayByFormulaId,
    scopedRestaurantId: runtime.scopedRestaurantId,
    hasMissingColumnError: helpers.hasMissingColumnError,
    normalizeFormulaStepEntries: helpers.normalizeFormulaStepEntries,
    buildDishStepMapFromFormulaSteps: helpers.buildDishStepMapFromFormulaSteps,
    buildFormulaStepsFromDishStepMap: helpers.buildFormulaStepsFromDishStepMap,
    parseExtrasFromUnknown: helpers.parseExtrasFromUnknown,
    normalizeText: helpers.normalizeText,
    allergenLibrary: core.allergenLibrary,
    mergeExtrasUnique: helpers.mergeExtrasUnique,
    createLocalId: helpers.createLocalId,
    parseDishOptionsRowsToExtras: helpers.parseDishOptionsRowsToExtras,
    parseI18nToken: helpers.parseI18nToken,
    getDishDisplayDescription: helpers.getDishDisplayDescription,
    parseDishAvailableDays: helpers.parseDishAvailableDays,
    normalizeTimeInput: helpers.normalizeTimeInput,
  };
}
