export function buildManagerViewPropsArgs(params: any) {
  const { bundles, runtime, state, setters, helpers, constants } = params;
  return {
    ...bundles.managerEditorUiState,
    ...bundles.managerUiLabels,
    ...bundles.managerStatsLabels,
    ...bundles.managerReviewInsights,
    ...bundles.managerAnalyticsRuntime,
    ...bundles.managerRestaurantLinks,
    ...bundles.managerMenuCrud,
    ...bundles.managerAdminActions,
    ...bundles.managerDishCollections,
    ...bundles.managerFormulaEditor,
    ...bundles.managerDishAssetsAndBadges,
    ...bundles.managerDishFormLifecycle,
    ...bundles.managerDishEditorLoad,
    ...bundles.managerDishSave,
    ...bundles.managerPrintActions,
    ...bundles.managerPdfReports,
    activeManagerTab: runtime.activeManagerTab,
    analyticsRange: runtime.analyticsRange,
    analyticsTab: runtime.analyticsTab,
    categories: state.categories,
    dishes: state.dishes,
    subCategoryRows: state.subCategoryRows,
    sides: state.sides,
    sidesLibrary: state.sidesLibrary,
    scopedRestaurantId: runtime.scopedRestaurantId,
    router: runtime.router,
    restaurant: state.restaurant,
    restaurantForm: state.restaurantForm,
    reviews: state.reviews,
    activeLanguageCodes: state.activeLanguageCodes,
    languageLabels: state.languageLabels,
    languagePresetToAdd: state.languagePresetToAdd,
    allergenLibrary: state.allergenLibrary,
    newAllergenFr: state.newAllergenFr,
    cookingTranslations: state.cookingTranslations,
    autoPrintKitchen: state.autoPrintKitchen,
    consultationModeEnabled: state.consultationModeEnabled,
    searchBarEnabled: state.searchBarEnabled,
    showCaloriesClient: state.showCaloriesClient,
    heroEnabled: state.heroEnabled,
    heroBadgeType: state.heroBadgeType,
    totalTables: state.totalTables,
    managerUserEmail: state.managerUserEmail,
    managerOtpEnabled: state.managerOtpEnabled,
    managerOtpError: state.managerOtpError,
    managerOtpLoading: state.managerOtpLoading,
    managerOtpMessage: state.managerOtpMessage,
    passwordForm: state.passwordForm,
    passwordUpdateError: state.passwordUpdateError,
    passwordUpdateLoading: state.passwordUpdateLoading,
    passwordUpdateMessage: state.passwordUpdateMessage,
    globalManagerNotification: state.globalManagerNotification,
    isRestaurantLoading: state.isRestaurantLoading,
    managerAccessError: state.managerAccessError,
    forceFirstLoginPasswordChange: state.forceFirstLoginPasswordChange,
    isPurgingHistory: state.isPurgingHistory,
    setActiveManagerTab: setters.setActiveManagerTab,
    setAnalyticsRange: setters.setAnalyticsRange,
    setAnalyticsTab: setters.setAnalyticsTab,
    setTotalTables: setters.setTotalTables,
    setRestaurantForm: setters.setRestaurantForm,
    setActiveLanguageCodes: setters.setActiveLanguageCodes,
    setLanguageLabels: setters.setLanguageLabels,
    setLanguagePresetToAdd: setters.setLanguagePresetToAdd,
    setAutoPrintKitchen: setters.setAutoPrintKitchen,
    setConsultationModeEnabled: setters.setConsultationModeEnabled,
    setCookingTranslations: setters.setCookingTranslations,
    setHeroBadgeType: setters.setHeroBadgeType,
    setHeroEnabled: setters.setHeroEnabled,
    setSearchBarEnabled: setters.setSearchBarEnabled,
    setShowCaloriesClient: setters.setShowCaloriesClient,
    setNewAllergenFr: setters.setNewAllergenFr,
    setPasswordForm: setters.setPasswordForm,
    setShowDeleteModal: setters.setShowDeleteModal,
    setDishToDelete: setters.setDishToDelete,
    renderReviewStars: helpers.renderReviewStars,
    formatEuro: helpers.formatEuro,
    toBoolean: helpers.toBoolean,
    parseI18nToken: helpers.parseI18nToken,
    normalizeText: helpers.normalizeText,
    normalizeLanguageKey: helpers.normalizeLanguageKey,
    normalizeTotalTables: helpers.normalizeTotalTables,
    normalizeCategoryDestination: helpers.normalizeCategoryDestination,
    normalizeSortOrder: helpers.normalizeSortOrder,
    normalizeCardStyle: helpers.normalizeCardStyle,
    normalizeManagerFontFamily: helpers.normalizeManagerFontFamily,
    normalizeOpacityPercent: helpers.normalizeOpacityPercent,
    normalizeWelcomePopupType: helpers.normalizeWelcomePopupType,
    parseObjectRecord: helpers.parseObjectRecord,
    MAX_TOTAL_TABLES: constants.MAX_TOTAL_TABLES,
    DEFAULT_TOTAL_TABLES: constants.DEFAULT_TOTAL_TABLES,
    DEFAULT_LANGUAGE_LABELS: constants.DEFAULT_LANGUAGE_LABELS,
    DEFAULT_COOKING_TRANSLATIONS: constants.DEFAULT_COOKING_TRANSLATIONS,
    COOKING_TRANSLATION_ORDER: constants.COOKING_TRANSLATION_ORDER,
    MENU_FONT_OPTIONS: constants.MENU_FONT_OPTIONS,
    PREDEFINED_LANGUAGE_OPTIONS: constants.PREDEFINED_LANGUAGE_OPTIONS,
    DISH_AVAILABLE_DAY_OPTIONS: constants.DISH_AVAILABLE_DAY_OPTIONS,
    HUNGER_LEVELS: constants.HUNGER_LEVELS,
    STANDARD_FORMULA_ALLERGENS: constants.STANDARD_FORMULA_ALLERGENS,
    ALLERGEN_OPTIONS: constants.ALLERGEN_OPTIONS,
    FORMULA_PARENT_STEP_KEY: constants.FORMULA_PARENT_STEP_KEY,
    FORMULA_DIRECT_SEND_SEQUENCE: constants.FORMULA_DIRECT_SEND_SEQUENCE,
  };
}
