import type { Metadata } from "next";
import "./globals.css";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" style={{ backgroundColor: "transparent", colorScheme: "light" }}>
      <head>
        <meta charSet="utf-8" />
      </head>
      <body style={{ backgroundColor: "transparent", colorScheme: "light" }}>
        {children}
      </body>
    </html>
  );
}

