// @ts-nocheck

export const dishEditorModalUiTranslations = {
  "manager.dish_editor.tabs.general": "Général",
  "manager.dish_editor.tabs.options": "Options & Variantes",
  "manager.dish_editor.tabs.formula": "Formule",
} as const;

export const buildDishEditorModalT = (key: string) =>
  (dishEditorModalUiTranslations as Record<string, string>)[key] || "";

export function buildDishEditorModalProps(c: any) {
  return {
    showDishModal: c.showDishModal,
    setShowDishModal: c.setShowDishModal,
    editingDish: c.editingDish,
    activeManagerTab: c.activeManagerTab,
    t: buildDishEditorModalT,
    translations: dishEditorModalUiTranslations,
    activeDishModalTab: c.activeDishModalTab,
    setActiveDishModalTab: c.setActiveDishModalTab,
    formData: c.formData,
    setFormData: c.setFormData,
    activeLanguageCodes: c.activeLanguageCodes,
    openDishLanguagePanels: c.openDishLanguagePanels,
    allergenLibrary: c.allergenLibrary,
    imagePreviewUrl: c.imagePreviewUrl,
    isUploadingImage: c.isUploadingImage,
    handleDishImageUpload: c.handleDishImageUpload,
    getDefaultSuggestionLead: c.getDefaultSuggestionLead,
    toggleDishLanguagePanel: c.toggleDishLanguagePanel,
    sortedCategories: c.sortedCategories,
    categories: c.categories,
    subCategoryRows: c.subCategoryRows,
    getCategoryLabel: c.getCategoryLabel,
    DISH_AVAILABLE_DAY_OPTIONS: c.DISH_AVAILABLE_DAY_OPTIONS,
    HUNGER_LEVELS: c.HUNGER_LEVELS,
    STANDARD_FORMULA_ALLERGENS: c.STANDARD_FORMULA_ALLERGENS,
    ALLERGEN_OPTIONS: c.ALLERGEN_OPTIONS,
    selectedDishLanguageCode: c.selectedDishLanguageCode,
    setSelectedDishLanguageCode: c.setSelectedDishLanguageCode,
    normalizeLanguageKey: c.normalizeLanguageKey,
    languageLabels: c.languageLabels,
    DEFAULT_LANGUAGE_LABELS: c.DEFAULT_LANGUAGE_LABELS,
    selectedOptionLanguageCode: c.selectedOptionLanguageCode,
    setSelectedOptionLanguageCode: c.setSelectedOptionLanguageCode,
    productOptionDraft: c.productOptionDraft,
    setProductOptionDraft: c.setProductOptionDraft,
    editingProductOptionId: c.editingProductOptionId,
    setEditingProductOptionId: c.setEditingProductOptionId,
    handleAddProductOptionToDish: c.handleAddProductOptionToDish,
    handleEditProductOptionInDish: c.handleEditProductOptionInDish,
    handleRemoveProductOptionFromDish: c.handleRemoveProductOptionFromDish,
    selectedExtraLanguageCode: c.selectedExtraLanguageCode,
    setSelectedExtraLanguageCode: c.setSelectedExtraLanguageCode,
    dishExtraDraft: c.dishExtraDraft,
    setDishExtraDraft: c.setDishExtraDraft,
    editingExtraId: c.editingExtraId,
    setEditingExtraId: c.setEditingExtraId,
    setEditingExtraOriginKey: c.setEditingExtraOriginKey,
    handleAddExtraToDish: c.handleAddExtraToDish,
    handleEditExtraInDish: c.handleEditExtraInDish,
    handleRemoveExtraFromDish: c.handleRemoveExtraFromDish,
    formulaSupplementsSaveStatus: c.formulaSupplementsSaveStatus,
    handleSaveFormulaSupplements: c.handleSaveFormulaSupplements,
    formulaDescription: c.formulaDescription,
    setFormulaDescription: c.setFormulaDescription,
    formulaImage: c.formulaImage,
    setFormulaImage: c.setFormulaImage,
    isUploadingFormulaImage: c.isUploadingFormulaImage,
    formulaImagePreviewUrl: c.formulaImagePreviewUrl,
    handleFormulaImageUpload: c.handleFormulaImageUpload,
    selectedFormulaLanguageCode: c.selectedFormulaLanguageCode,
    setSelectedFormulaLanguageCode: c.setSelectedFormulaLanguageCode,
    formulaKcal: c.formulaKcal,
    setFormulaKcal: c.setFormulaKcal,
    formulaAllergens: c.formulaAllergens,
    setFormulaAllergens: c.setFormulaAllergens,
    formulaVisibilitySaveStatus: c.formulaVisibilitySaveStatus,
    setFormulaVisibilitySaveStatus: c.setFormulaVisibilitySaveStatus,
    handleSaveFormulaVisibility: c.handleSaveFormulaVisibility,
    formulaSelectableDishGroups: c.formulaSelectableDishGroups,
    selectedFormulaDishes: c.selectedFormulaDishes,
    setSelectedFormulaDishes: c.setSelectedFormulaDishes,
    readFormulaDefaultOptionIdsMap: c.readFormulaDefaultOptionIdsMap,
    dishSteps: c.dishSteps,
    setDishSteps: c.setDishSteps,
    FORMULA_PARENT_STEP_KEY: c.FORMULA_PARENT_STEP_KEY,
    mainDishStep: c.mainDishStep,
    setMainDishStep: c.setMainDishStep,
    updateStep: c.updateStep,
    preparedDishesSorted: c.preparedDishesSorted,
    getLanguageColumnKeys: c.getLanguageColumnKeys,
    handleFormulaDefaultOptionToggle: c.handleFormulaDefaultOptionToggle,
    selectedMainDishOptions: c.selectedMainDishOptions,
    handleToggleExcludedMainOption: c.handleToggleExcludedMainOption,
    handleSaveExcludedMainOptions: c.handleSaveExcludedMainOptions,
    mainOptionsSaveStatus: c.mainOptionsSaveStatus,
    addStep: c.addStep,
    removeStep: c.removeStep,
    FORMULA_DIRECT_SEND_SEQUENCE: c.FORMULA_DIRECT_SEND_SEQUENCE,
    isRadarLoaded: c.isRadarLoaded,
    formulaDishes: c.formulaDishes,
    dishes: c.dishes,
    sidesLibrary: c.sidesLibrary,
    sides: c.sides,
    parseI18nToken: c.parseI18nToken,
    toBoolean: c.toBoolean,
    normalizeText: c.normalizeText,
    formatEuro: c.formatEuro,
    handleBadgeSwitchChange: c.handleBadgeSwitchChange,
    handleSave: c.handleSave,
    dishSaveStatus: c.dishSaveStatus,
    resetForm: c.resetForm,
  };
}

export function buildManagerAppearancePanelProps(c: any) {
  return {
    COOKING_TRANSLATION_ORDER: c.COOKING_TRANSLATION_ORDER,
    DEFAULT_COOKING_TRANSLATIONS: c.DEFAULT_COOKING_TRANSLATIONS,
    DEFAULT_LANGUAGE_LABELS: c.DEFAULT_LANGUAGE_LABELS,
    MAX_TOTAL_TABLES: c.MAX_TOTAL_TABLES,
    MENU_FONT_OPTIONS: c.MENU_FONT_OPTIONS,
    PREDEFINED_LANGUAGE_OPTIONS: c.PREDEFINED_LANGUAGE_OPTIONS,
    activeLanguageCodes: c.activeLanguageCodes,
    activeManagerTab: c.activeManagerTab,
    allergenLibrary: c.allergenLibrary,
    autoPrintKitchen: c.autoPrintKitchen,
    bannerColorLabel: c.bannerColorLabel,
    bannerImageLabel: c.bannerImageLabel,
    consultationModeEnabled: c.consultationModeEnabled,
    cookingTranslations: c.cookingTranslations,
    createLocalId: c.createLocalId,
    dishCardsColorLabel: c.dishCardsColorLabel,
    dishCardsOpacityLabel: c.dishCardsOpacityLabel,
    dishCardsTextColorLabel: c.dishCardsTextColorLabel,
    globalTextColorLabel: c.globalTextColorLabel,
    handleDeleteAllergen: c.handleDeleteAllergen,
    handleSaveRestaurant: c.handleSaveRestaurant,
    heroBadgeType: c.heroBadgeType,
    heroEnabled: c.heroEnabled,
    isUploadingRestaurantBackground: c.isUploadingRestaurantBackground,
    isUploadingRestaurantBanner: c.isUploadingRestaurantBanner,
    isUploadingRestaurantLogo: c.isUploadingRestaurantLogo,
    isUploadingRestaurantWelcome: c.isUploadingRestaurantWelcome,
    languageLabels: c.languageLabels,
    languagePresetToAdd: c.languagePresetToAdd,
    newAllergenFr: c.newAllergenFr,
    normalizeCardStyle: c.normalizeCardStyle,
    normalizeLanguageKey: c.normalizeLanguageKey,
    normalizeManagerFontFamily: c.normalizeManagerFontFamily,
    normalizeOpacityPercent: c.normalizeOpacityPercent,
    normalizeText: c.normalizeText,
    normalizeTotalTables: c.normalizeTotalTables,
    normalizeWelcomePopupType: c.normalizeWelcomePopupType,
    openManagerPanels: c.openManagerPanels,
    restaurantForm: c.restaurantForm,
    searchBarEnabled: c.searchBarEnabled,
    setActiveLanguageCodes: c.setActiveLanguageCodes,
    setAllergenLibrary: c.setAllergenLibrary,
    setAutoPrintKitchen: c.setAutoPrintKitchen,
    setConsultationModeEnabled: c.setConsultationModeEnabled,
    setCookingTranslations: c.setCookingTranslations,
    setDishExtraDraft: c.setDishExtraDraft,
    setFormData: c.setFormData,
    setHeroBadgeType: c.setHeroBadgeType,
    setHeroEnabled: c.setHeroEnabled,
    setLanguageLabels: c.setLanguageLabels,
    setLanguagePresetToAdd: c.setLanguagePresetToAdd,
    setNewAllergenFr: c.setNewAllergenFr,
    setNewSideI18n: c.setNewSideI18n,
    setRestaurantForm: c.setRestaurantForm,
    setSearchBarEnabled: c.setSearchBarEnabled,
    setShowCaloriesClient: c.setShowCaloriesClient,
    setSideFormI18n: c.setSideFormI18n,
    setTotalTables: c.setTotalTables,
    showCaloriesClient: c.showCaloriesClient,
    restaurantSaveStatus: c.restaurantSaveStatus,
    toggleManagerPanel: c.toggleManagerPanel,
    totalTables: c.totalTables,
    uploadRestaurantAsset: c.uploadRestaurantAsset,
  };
}

export function buildManagerStatsPanelProps(c: any) {
  return {
    activeManagerTab: c.activeManagerTab,
    analyticsRange: c.analyticsRange,
    analyticsTab: c.analyticsTab,
    analyticsText: c.analyticsText,
    avgCoversPerTableLabel: c.avgCoversPerTableLabel,
    avgDurationColumnLabel: c.avgDurationColumnLabel,
    avgOccupationRateLabel: c.avgOccupationRateLabel,
    avgRevenuePerHourLabel: c.avgRevenuePerHourLabel,
    avgTableDurationLabel: c.avgTableDurationLabel,
    avgTicketPerCoverLabel: c.avgTicketPerCoverLabel,
    dailyServiceDetailsLabel: c.dailyServiceDetailsLabel,
    dateColumnLabel: c.dateColumnLabel,
    displayedAnalytics: c.displayedAnalytics,
    formatEuro: c.formatEuro,
    fullSalesInventoryLabel: c.fullSalesInventoryLabel,
    generatedRevenueLabel: c.generatedRevenueLabel,
    handleCloseMonthAndPurge: c.handleCloseMonthAndPurge,
    handleExportMonthlyReportPdfArchive: c.handleExportMonthlyReportPdfArchive,
    isPurgingHistory: c.isPurgingHistory,
    monthlyCloseEnabled: c.monthlyCloseEnabled,
    mostProfitableHourLabel: c.mostProfitableHourLabel,
    ordersColumnLabel: c.ordersColumnLabel,
    peakOrdersLabel: c.peakOrdersLabel,
    quantitySoldLabel: c.quantitySoldLabel,
    SafeResponsiveContainer: c.SafeResponsiveContainer,
    setAnalyticsRange: c.setAnalyticsRange,
    setAnalyticsTab: c.setAnalyticsTab,
    soldUnitsLabel: c.soldUnitsLabel,
    weekColumnLabel: c.weekColumnLabel,
    weeklyAverageSummaryLabel: c.weeklyAverageSummaryLabel,
    weeklyEvolutionLabel: c.weeklyEvolutionLabel,
  };
}

export function buildManagerMenuPanelProps(c: any) {
  return {
    ManagerStatsPanel: c.ManagerStatsPanel,
    activeLanguageCodes: c.activeLanguageCodes,
    activeManagerTab: c.activeManagerTab,
    categories: c.categories,
    dishes: c.dishes,
    editingSubCategoryId: c.editingSubCategoryId,
    formatEuro: c.formatEuro,
    getCategoryLabel: c.getCategoryLabel,
    handleAddDish: c.handleAddDish,
    handleCreateSide: c.handleCreateSide,
    handleCreateSubCategory: c.handleCreateSubCategory,
    handleDeleteCategory: c.handleDeleteCategory,
    handleDeleteDish: c.handleDeleteDish,
    handleDeleteSide: c.handleDeleteSide,
    handleDeleteSubCategory: c.handleDeleteSubCategory,
    handleEditDish: c.handleEditDish,
    handleEditSide: c.handleEditSide,
    handleGeneratePrintableMenu: c.handleGeneratePrintableMenu,
    handleToggleDishHighlight: c.handleToggleDishHighlight,
    handleUpdateCategoryDestination: c.handleUpdateCategoryDestination,
    handleUpdateCategorySortOrder: c.handleUpdateCategorySortOrder,
    managerStatsPanelProps: c.managerStatsPanelProps,
    newSide: c.newSide,
    newSideI18n: c.newSideI18n,
    newSubCategory: c.newSubCategory,
    newSubCategoryI18n: c.newSubCategoryI18n,
    normalizeCategoryDestination: c.normalizeCategoryDestination,
    normalizeSortOrder: c.normalizeSortOrder,
    parseI18nToken: c.parseI18nToken,
    preparedDishesGroupedByCategory: c.preparedDishesGroupedByCategory,
    router: c.router,
    scopedRestaurantId: c.scopedRestaurantId,
    setCategoryForm: c.setCategoryForm,
    setCategoryFormI18n: c.setCategoryFormI18n,
    setCategorySaveStatus: c.setCategorySaveStatus,
    setEditingCategoryId: c.setEditingCategoryId,
    setEditingSubCategoryId: c.setEditingSubCategoryId,
    setNewSide: c.setNewSide,
    setNewSideI18n: c.setNewSideI18n,
    setNewSubCategory: c.setNewSubCategory,
    setNewSubCategoryI18n: c.setNewSubCategoryI18n,
    setShowCategoryModal: c.setShowCategoryModal,
    sideSaveStatus: c.sideSaveStatus,
    sides: c.sides,
    sortedCategories: c.sortedCategories,
    subCategoryRows: c.subCategoryRows,
    toBoolean: c.toBoolean,
  };
}

export function buildManagerStaffAndRoomsProps(c: any) {
  return {
    MAX_TOTAL_TABLES: c.MAX_TOTAL_TABLES,
    activeManagerTab: c.activeManagerTab,
    normalizeTotalTables: c.normalizeTotalTables,
    router: c.router,
    scopedRestaurantId: c.scopedRestaurantId,
    setTotalTables: c.setTotalTables,
    totalTables: c.totalTables,
  };
}

export function buildManagerCategorySideModalsProps(c: any) {
  return {
    activeLanguageCodes: c.activeLanguageCodes,
    categoryForm: c.categoryForm,
    categoryFormI18n: c.categoryFormI18n,
    categorySaveStatus: c.categorySaveStatus,
    editingCategoryId: c.editingCategoryId,
    handleCreateCategory: c.handleCreateCategory,
    handleSaveSide: c.handleSaveSide,
    normalizeCategoryDestination: c.normalizeCategoryDestination,
    setCategoryForm: c.setCategoryForm,
    setCategoryFormI18n: c.setCategoryFormI18n,
    setCategorySaveStatus: c.setCategorySaveStatus,
    setEditingCategoryId: c.setEditingCategoryId,
    setEditingSideId: c.setEditingSideId,
    setShowCategoryModal: c.setShowCategoryModal,
    setShowSideModal: c.setShowSideModal,
    setSideForm: c.setSideForm,
    setSideFormI18n: c.setSideFormI18n,
    setSideSaveStatus: c.setSideSaveStatus,
    showCategoryModal: c.showCategoryModal,
    showSideModal: c.showSideModal,
    sideForm: c.sideForm,
    sideFormI18n: c.sideFormI18n,
    sideSaveStatus: c.sideSaveStatus,
  };
}

export function buildManagerAccessAlertsProps(c: any) {
  return {
    globalManagerNotification: c.globalManagerNotification,
    isRestaurantLoading: c.isRestaurantLoading,
    managerAccessError: c.managerAccessError,
  };
}

export function buildManagerHeaderSectionProps(c: any) {
  return {
    ManagerMenuPanel: c.ManagerMenuPanel,
    activeManagerTab: c.activeManagerTab,
    handleManagerSignOut: c.handleManagerSignOut,
    managerMenuPanelProps: c.managerMenuPanelProps,
    router: c.router,
    scopedRestaurantId: c.scopedRestaurantId,
    setActiveManagerTab: c.setActiveManagerTab,
  };
}

export function buildManagerOverlaysProps(c: any) {
  return {
    confirmDeleteDish: c.confirmDeleteDish,
    dishToDelete: c.dishToDelete,
    forceFirstLoginPasswordChange: c.forceFirstLoginPasswordChange,
    handleUpdateManagerPassword: c.handleUpdateManagerPassword,
    managerCategorySideModalsProps: c.managerCategorySideModalsProps,
    passwordForm: c.passwordForm,
    passwordUpdateError: c.passwordUpdateError,
    passwordUpdateLoading: c.passwordUpdateLoading,
    passwordUpdateMessage: c.passwordUpdateMessage,
    printFrameRef: c.printFrameRef,
    setDishToDelete: c.setDishToDelete,
    setPasswordForm: c.setPasswordForm,
    setShowDeleteModal: c.setShowDeleteModal,
    showDeleteModal: c.showDeleteModal,
  };
}

export function buildManagerDashboardSectionProps(c: any) {
  return {
    AppearanceUI: c.AppearanceUI,
    CardDesigner: c.CardDesigner,
    ConfigGeneral: c.ConfigGeneral,
    ConfigMail: c.ConfigMail,
    ConfigSocials: c.ConfigSocials,
    RestaurantQrCard: c.RestaurantQrCard,
    StaffAndRooms: c.StaffAndRooms,
    activeManagerTab: c.activeManagerTab,
    cardDesignerProps: c.cardDesignerProps,
    currentRestaurantPublicUrl: c.currentRestaurantPublicUrl,
    currentRestaurantQrId: c.currentRestaurantQrId,
    currentRestaurantVitrineUrl: c.currentRestaurantVitrineUrl,
    dishNameById: c.dishNameById,
    dishReviews: c.dishReviews,
    handlePrintWeeklyReviewsReportPdf: c.handlePrintWeeklyReviewsReportPdf,
    handleSaveRestaurant: c.handleSaveRestaurant,
    handleToggleManagerOtp: c.handleToggleManagerOtp,
    handleUpdateManagerPassword: c.handleUpdateManagerPassword,
    managerAppearancePanelProps: c.managerAppearancePanelProps,
    managerStaffAndRoomsProps: c.managerStaffAndRoomsProps,
    managerOtpEnabled: c.managerOtpEnabled,
    managerOtpError: c.managerOtpError,
    managerOtpLoading: c.managerOtpLoading,
    managerOtpMessage: c.managerOtpMessage,
    managerUserEmail: c.managerUserEmail,
    passwordForm: c.passwordForm,
    passwordUpdateError: c.passwordUpdateError,
    passwordUpdateLoading: c.passwordUpdateLoading,
    passwordUpdateMessage: c.passwordUpdateMessage,
    renderReviewStars: c.renderReviewStars,
    restaurant: c.restaurant,
    restaurantForm: c.restaurantForm,
    restaurantReviews: c.restaurantReviews,
    restaurantSaveStatus: c.restaurantSaveStatus,
    reviewAverage: c.reviewAverage,
    reviews: c.reviews,
    setPasswordForm: c.setPasswordForm,
    topReviewedDish: c.topReviewedDish,
    vitrineViewsCount: c.vitrineViewsCount,
    weeklyAiSummary: c.weeklyAiSummary,
  };
}
