export type Item = {
  id: string | number;
  order_item_id?: string | number | null;
  dish_id: string | number;
  category_id?: string | number | null;
  dish: { id: string | number; name_fr: string; name: string };
  name: string;
  name_fr?: string;
  label?: string;
  product_name?: string;
  quantity: number;
  categorie: string;
  category: string;
  instructions: string;
  cooking?: string | null;
  cuisson?: string | null;
  side?: unknown;
  accompagnement?: unknown;
  accompagnements?: unknown;
  side_dish?: unknown;
  sideDish?: unknown;
  selected_options?: unknown;
  options?: unknown;
  selected_option?: unknown;
  selected_option_id?: string | number | null;
  selected_option_name?: string | null;
  selected_option_price?: number | null;
  selectedOptions?: unknown;
  selected_side_ids: Array<string | number>;
  selected_extra_ids: Array<string | number>;
  selected_extras: Array<{ id: string; label_fr: string; name: string; name_fr: string; price: number }>;
  selected_cooking_key: string | null;
  selected_cooking_label_fr: string | null;
  selected_cooking_label?: string | null;
  selected_cooking_label_pt?: string | null;
  selected_cooking: string | null;
  is_formula?: boolean | null;
  formula_id?: string | number | null;
  formula_dish_id?: string | number | null;
  formula_name?: string | null;
  formula_dish_name?: string | null;
  formula_current_sequence?: number | null;
  step?: number | null;
  sequence?: number | null;
  selected_side_label_fr?: string | null;
  selected_side_label?: string | null;
  selected_side_label_pt?: string | null;
  special_request: string | null;
  selectedSides: Array<string | number>;
  selectedExtras: Array<{ name: string; name_fr: string; price: number }>;
  status?: string | null;
};

export type Order = {
  id: string;
  table_number: string;
  items: any;
  order_items?: any[] | null;
  status: string;
  created_at: string;
  service_step?: string | null;
  current_step?: number | null;
  covers?: number | null;
  guest_count?: number | null;
  customer_count?: number | null;
  restaurant_id?: string | number | null;
};

export type KitchenMessage = {
  id: string;
  restaurant_id?: string | number | null;
  message?: string | null;
  content?: string | null;
  note?: string | null;
  sender_name?: string | null;
  is_active?: boolean | null;
  created_at?: string | null;
};

